dist: precise
language: php

php:
- 7.4.2

addons:
        mariadb: 10.4.11

before_script:
- cp .env.travis .env
- sudo mysql -e 'create database library;'
- composer self-update
- composer install --no-interaction
- php artisan migrate --no-interaction -vvv 

script:
    - vendor/bin/phpunit

notifications:
email:
    recipients:
        - jazzonahimana@gmail.com
    on_success: always
    on_failure: always