os: linux
language: php
php: '7.4.2'
services:
        - mysql
before_script:
        - composer self-update
        - composer install --no-interaction
        - mysql -e 'CREATE DATABASE library'
        - npm install 
        - cp .env.travis .env
        - php artisan key:generate
        - php artisan migrate

script:
        - ./vendor/bin/phpunit
        - npm run production
notifications:
email:
        recipients:
        - jazzonahimana@gmail.com
   on_success: always
   on_failure: always
